- CHANGELOG.md
- mix.exs
- mix.lock
Bump mix.exs version number and update astarte_rpc library to release-0.11
branch.
> Prepare 0.11.0-beta.1 release

- lib/astarte_vmq_plugin/rpc/handler.ex
> rpc/handler: do not rely on defaults

- CHANGELOG.md
- lib/astarte_vmq_plugin.ex
- lib/astarte_vmq_plugin/config.ex
- priv/astarte_vmq_plugin.schema
Send an heartbeat to refresh device connection state and to allow DUP to handle
disconnections happened while VerneMQ was down.
Fix #13
> Send periodic heartbeat for each connected device

- .github/workflows/pr-container-build-workflow.yaml
- CHANGELOG.md
- Dockerfile
Copy the plugin from the current directory instead of using git clone. This way
we ensure we're building the correct version in every branch.
While we're at it, add the build optimizations that are already present in other
Dockerfiles.
Note that this requires a change of settins on Dockerhub.
> Dockerfile: move to root and enhance build process

- docker/bin/vernemq.sh
- docker/files/vernemq.conf
Fix crash when an instance that was not using SSL (e.g. on Kubernetes) was
brought up.
> Write SSL configuration to vernemq.conf only if SSL is enabled

- CHANGELOG.md
- lib/astarte_vmq_plugin/config.ex
The erlang default of 1 is too strict. Increase the default value to 10
to make it coincident to OpenSSL default.
> Default max certificate chain length to 10

- CHANGELOG.md
- Dockerfile
- lib/astarte_vmq_plugin/rpc/handler.ex
- mix.lock
- test/astarte_vmq_plugin_rpc_test.exs
Allow the caller to react based on the actual number of clients that will (eventually) receive the published data
> Reply to publish requests with local and remote matches

- CHANGELOG.md
- docker/files/vernemq.conf
With https://github.com/astarte-platform/astarte/pull/386 AppEngine now
makes sure the message gets delivered to the device before returning
200.
persistent_client_expiration and max_offline_messages influence this
behavior, since they limit the lifetime and quantity of messages that
will be delivered to the device.
Therefore, these values are made tunable via the docker env vars
mechanism.
> Remove explicit persistency defaults, allow to configure them

- CHANGELOG.md
- lib/astarte_vmq_plugin/rpc/handler.ex
- test/astarte_vmq_plugin_rpc_test.exs
With the old protobufs, the default value for not-set payload for nil, which was
an invalid one. When converting to Protobuf 3 with
02b97b8999e28aabb8b47934fa6c11071897ccd4 the default value changed from nil to
an empty string, but an empty string is effectively a valid payload (e.g. for an
unset message), so we have to remove the clause marking the value as invalid.
Fixes https://github.com/astarte-platform/astarte/issues/460
> Allow empty payload in publish

- .github/workflows/build-workflow.yaml
- CHANGELOG.md
- mix.exs
- src/astarte_vmq_plugin.erl
We want to start the plugin as permanent to make sure that if the plugin application crashes, VerneMQ comes down with it (and gets restarted by K8s).
To do so, we need to define an erlang wrapper since right now VerneMQ assumes the custom start function is contained in a module with the same name as the application, which can't be an Elixir module due to naming constraints.
This should fix the situations where VerneMQ was not able to publish after a RabbitMQ disconnection causing a plugin crash.
> Start the plugin OTP application as permanent

- CHANGELOG.md
- lib/astarte_vmq_plugin.ex
- test/astarte_vmq_plugin_test.exs
Fix #1 . 
Now the Plugin returns `:next` instead of `:ok `in `auth_on_publish` and `auth_on_subscribe` when the username doesn't contain a `/ `(and so it is not considered a device).
> Do not authorize non-devices blindly in auth_on_publish and auth_on_subscribe

- CHANGELOG.md
- lib/astarte_vmq_plugin.ex
Do not override the `max_message_rate` value from VMQ config in the return tuple of `auth_on_register`.
> Remove `max_message_rate` from `auth_on_register` return tuple

- Dockerfile
The `git` protocol is no more supported by Github for security reasons (see [here](https://github.blog/2021-09-01-improving-git-protocol-security-github/)). Replace it by `https`.
See the [related issue](https://github.com/vernemq/vernemq/issues/1949) on VMQ repo.
> Dockerfile: use `https` instead of unsupported `git` protocol

- CHANGELOG.md
- docker/bin/vernemq.sh
The vernemq container isn't allowed to start unless the ca cert is
obtained from cfssl.
> Fail if the CA cert cannot be retrieved from CFSSL

- CHANGELOG.md
- Dockerfile
- docker/patches/increase_ssl_handshake_timeout.patch
This is a temporary workaround to allow constrained devices that take more than 5 seconds to perform the SSL handshake to connect to the broker without timing out.
See https://github.com/vernemq/vernemq/issues/1670 for the related issue, this will be reverted once the configuration for the handshake timeout is exposed in VerneMQ
Signed-off-by: Riccardo Binetti <riccardo.binetti@secomind.com>
> Add a patch to increase SSL handshake timeout in VerneMQ

- CHANGELOG.md
- lib/astarte_vmq_plugin.ex
- lib/astarte_vmq_plugin/application.ex
- lib/astarte_vmq_plugin/connection/synchronizer.ex
- lib/astarte_vmq_plugin/connection/synchronizer/synchronizer_supervisor.ex
- test/astarte_vmq_plugin_connection_synchronizer_test.exs
- test/astarte_vmq_plugin_test.exs
In rare corner cases (time difference < 10 ms), the `on_register` hook (reconnection) may be called before the related `on_client_offline/gone` hook (disconnection). This is due to the distributed nature of VerneMQ (see https://github.com/vernemq/vernemq/issues/1741), and results in an invalid device connection state in Astarte: a device may be publishing while being in a disconnected status.
Introduce a check on the order of disconnection/reconnection events, and possibly reorder them if such a corner case happens.
During reordering (at most 50ms), other kind of messages (if any) are retained in VMQ memory. 
Fix https://github.com/astarte-platform/astarte/issues/668.
> Fix order of disconnection and connection events

- CHANGELOG.md
- lib/astarte_vmq_plugin.ex
- test/astarte_vmq_plugin_test.exs
Drop the `heartbeat` message type for a more general one.
> Use the `internal` event type for device heartbeat

- .github/workflows/build-workflow.yaml
- .github/workflows/pr-container-build-workflow.yaml
- .tool-versions
- CHANGELOG.md
- Dockerfile
- config/ci.exs
- config/config.exs
- config/dev.exs
- config/prod.exs
- config/test.exs
- mix.exs
- mix.lock
Bump Elixir and Erlang to 1.14.5 and 25.3.2, respectively. Contextually, fix formatting and remove deprecated `Mix.Config`.
Bump VerneMQ to 1.13.0.
Bump also base GH workflow tools.
> Bump Elixir, Erlang and VerneMQ 

- CHANGELOG.md
- lib/astarte_vmq_plugin/config.ex
- lib/astarte_vmq_plugin/queries.ex
- mix.lock
- priv/astarte_vmq_plugin.schema
- test/support/database_test_helper.ex
Plugin's queries have been rewritten to work with new keyspace separation logic, a feature that is going to be introduced in astarte.
This edit has become necessary after PR #75 that enabled db access for this repo.
Due to the small size of queries file, the entire keyspace selection is handled by a single private function use_realm/2, so translation is made here.
Also, a new env variable named `DOCKER_VERNEMQ_ASTARTE_VMQ_PLUGIN__ASTARTE_INSTANCE_ID` has been added, this works as astarte_instance_id in translation function (see https://github.com/astarte-platform/astarte_core/pull/105 for details), defaults to 'default' string.
Tests have been edited to match new db structure, so with a translated keyspace name (in this case, derived from a 'test' realm name).
This PR must not be merged …
> Queries edit for keyspace separation feature 

- .github/workflows/publish-release-to-dockerhub-workflow.yaml
- .github/workflows/publish-snapshot-to-dockerhub-workflow.yaml
Standardize the image publishing workflows to use Github rather than Dockerhub CI.
For all details, see https://github.com/astarte-platform/astarte/pull/960.
> Workflows: add build and push to Dockerhub workflow

- CHANGELOG.md
- lib/astarte_vmq_plugin.ex
- mix.lock
- test/astarte_vmq_plugin_test.exs
Devices can publish on `<realm>/<device_id>/capabilities` a message which will be forwarded with message type `capabilities`. This in the context of astarte-platform/astarte#1049 and allows DUP to receive the appropriate messages
> feat(capabilities): `capabilities` topic

- .github/workflows/publish-release-to-dockerhub-workflow.yaml
- .github/workflows/publish-snapshot-to-dockerhub-workflow.yaml
- Dockerfile
This change adds support for building the plugin targeting specific architectures.
The CI workflows are updated to setup buildx, a Docker CLI plugin for extended build capabilities with BuildKit, and to build multi-arch Docker images.
The targeted platforms are: linux/amd64 and linux/arm64.
> Setup CI for multi-arch builds

- docker/bin/vernemq.sh
This PR modifies the `vernemq.sh` entrypoint script to support dynamic configuration of the Erlang distribution cookie used for clustering VerneMQ nodes.
Key changes:
- The script now reads the `RELEASE_COOKIE` environment variable, if set, and injects it into the vm.args file at runtime.
- If `RELEASE_COOKIE` is not set, the behavior falls back to the default (previously set value `vmq` in vm.args), ensuring backward compatibility.
In our deployment architecture, each instance of Astarte (Elixir services + VerneMQ with the custom plugin) will require a possibly unique Erlang cookie to securely form a cluster between the Erlang nodes. This change enables per-instance configuration without modifying the Docker image or baked-in vm.args file.
> feat(docker): allow dynamic Erlang cookie via environment variable

- lib/astarte_vmq_plugin/rpc/supervisor.ex
RPC supervisor crashed when another rpc serve was already present in the distributed registry. With this PR the RPC server starts if no other server are in the registry and otherwise nothing happens :+1:
> fix: wrong supervisor behavior

- lib/astarte_vmq_plugin/rpc/server.ex
- lib/astarte_vmq_plugin/rpc/supervisor.ex
previously, we avoided adding the server as a child to the supervisor if a server existed already, leaving the job to horde to eventually create a consistent status between the supervisors.
now, we do the same while making sure the rpc server is always added as a child to the supervisor, so that it is not possible for it to just not start
fixed some typos while at it
> fix: ensure rpc server always starts
